---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dlogo
  namespace: se-joecolandro
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dlogo
  template:
    metadata:
      labels:
        app: dlogo
    spec:
      containers:
        - name: dlogo
          image: dtr.west.us.se.dckr.org/demo/dlogo:2019.10.07.195527-jc
          ports:
            - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: dlogo
  namespace: se-joecolandro
spec:
  selector:
    app: dlogo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: se-joecolandro
  name: dlogo-jcolandr-ingress
spec:
  rules:
  - host: dlogo.kube.west.us.se.dckr.org
    http:
      paths:
      - path: /
        backend:
          serviceName: dlogo
          servicePort: 80
